# setup

In [1]:
import sys

sys.path.append("../")

In [2]:
import json
import os
from typing import *

import dotenv
import pandas
from tqdm.notebook import tqdm

dotenv.load_dotenv()

True

In [3]:
from logging import Logger, StreamHandler, basicConfig

basicConfig(level="INFO", format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = Logger("notebook")
logger.addHandler(StreamHandler(sys.stdout))

logger.info("Hello, world!")

Hello, world!

In [4]:
%load_ext autoreload
%autoreload 2

# mysql

In [5]:
from crunch_titles._database import Database

if "database" in globals():
    database.__exit__(None, None, None) # type: ignore

database = Database(
    host=os.environ["DATABASE_HOST"],
    user=os.environ["DATABASE_USER"],
    password=os.environ["DATABASE_PASSWORD"],
    account_service_name=os.environ["ACCOUNT_DATABASE_NAME"],
    competition_service_name=os.environ["COMPETITION_DATABASE_NAME"],
    enable_caching=False,
)

database.__enter__()

In [6]:
from crunch_titles._repository import LoadEverythingRepository

repository = LoadEverythingRepository(
    database=database,
    logger=logger,
)

  0%|          | 0/13 [00:00<?, ?method/s]

load: competitions
load: users
load: leaderboard_definitions
load: targets
load: rounds
load: phases
load: crunches
load: crunch_targets
load: leaderboards
load: positions
load: paid_checkpoint_payouts
load: title_leaderboards
load: title_positions
len: _competitions=19
len: _competition_by_id=19
len: _competition_by_name=19
len: _user_by_id=2866
len: _user_by_login=2866
len: _default_leaderboard_definition_by_competition_id=21
len: _usable_targets_by_competition_id=22
len: _rounds_by_competition_id=21
len: _out_of_sample_phase_by_round_id=126
len: _published_crunch_by_phase_id=185
len: _crunch_target_by_crunch_id_and_target_id=954
len: _leaderboard_by_crunch_target_id_and_leaderboard_definition_id=712
len: _position_by_leaderboard_id=712
len: _payouts_by_competition_id=3
len: _payout_recipients_by_payout_id=45
len: _title_leaderboard_by_competition_id_and_year=0
len: _title_positions_by_leaderboard_id=0

# querying common data

In [7]:
competitions = repository.find_all_competitions()
competitions.sort(key=lambda x: x["name"] + " ")

for competition in competitions:
    print(competition["name"])

adialab
broad-1
broad-2
broad-3
broad-obesity-1
broad-obesity-2
broad-obesity-3
causality-discovery
datacrunch
datacrunch-2
datacrunch-rally
falcon
mid-one
numinous
structural-break
structural-break-open-benchmark
structural-break-real-time
synth
venture-capital-portfolio-prediction

In [8]:
structural_break = next(filter(lambda x: x["name"] == "structural-break", competitions))
structural_break_open_benchmark = next(filter(lambda x: x["name"] == "structural-break-open-benchmark", competitions), None)
datacrunch = next(filter(lambda x: x["name"] == "datacrunch", competitions))
falcon = next(filter(lambda x: x["name"] == "falcon", competitions))
structural_break2 = next(filter(lambda x: x["name"] == "structural-break-open-benchmark", competitions), None)

# compute positions

## compute positions from leaderboards

In [9]:
from crunch_titles._model import Competition
from crunch_titles._position import LeaderboardPosition, determine_positions

grouped_positions: List[Tuple[Tuple[Competition, int], List[LeaderboardPosition]]] = []

for competition in tqdm(competitions):
# for competition in tqdm([datacrunch]):
    grouped_positions.extend(determine_positions(
        competition=competition,
        repository=repository,
    ))

  0%|          | 0/19 [00:00<?, ?it/s]

### debug

In [10]:
from crunch_titles._debug import print_competition_positions_count

print_competition_positions_count(
    print,
    grouped_positions
)

competition                                        total    unique
adialab:0                                             375        1
broad-1:0                                              56        1
broad-2:0                                              16        1
broad-3:0                                              15        1
broad-obesity-1:0                                      67        1
broad-obesity-2:0                                      72        1
causality-discovery:0                                 207        1
datacrunch:2024                                      2101       26
datacrunch:2025                                      6380       50
datacrunch-rally:0                                     47        1
falcon:2025                                            96        6
falcon:2026                                           134        7
mid-one:2024                                           59        1
mid-one:2025                                           63        1
numinous:2026                                          91       12
structural-break:0                                    530        1
structural-break-open-benchmark:0                      97        1
venture-capital-portfolio-prediction:0                 58        1

## filter and average into a single point if necessary

In [11]:
from crunch_titles import LocalTitlePositionPerCompetitionYearList, average_leaderboards

averaged_leaderboards: LocalTitlePositionPerCompetitionYearList = []

for (competition, year), positions in grouped_positions:
    title_positions, user_count = average_leaderboards(
        competition=competition,
        year=year,
        positions=positions,
    )

    if len(title_positions):
        averaged_leaderboards.append(((competition, year), title_positions, user_count))

## merge

(only for structural-break/open-benchmark)

In [12]:
from crunch_titles import merge_leaderboards

merged_leaderboards = merge_leaderboards(
    repository=repository,
    averaged_leaderboards=averaged_leaderboards,
)

### debug

In [13]:
for (competition, year), positions, user_count in merged_leaderboards:
    if competition != datacrunch:
        continue

    print(competition["name"], year, len(positions), user_count)
    
    positions = list(positions)
    positions.sort(key=lambda x: x["rank"])

    for position in positions:
        print(f"{position["user"]["login"]:<30}  {position["rank"]:<3}")

datacrunch 2024 96 122
right-pachara                   1
selective-zhu                   2
spicy-questo                    3
tarandros                       3
amused-david                    3
vast-chananyu                   4
grubby-borit                    5
crowded-anirban                 6
trottefox                       7
giras                           7
semantic-hu                     7
soft-eduard                     8
video-taped-grzegorz            8
noob-saibot                     9
kain                            10
kat                             10
coolplay                        11
philosophical-ronny             11
bitter-krittanut                11
faithful-puretwin               11
ghiffaryr                       12
lcrm                            12
ltamas97                        12
cold-nasirudeen                 13
multiple-t                      13
substantial-alex                13
historic-joe                    13
duuscha                         13
wise-hbg                        14
alo                             15
fahrenheit                      15
magnetic-kansuke                15
yellow-filip                    15
anonymous-manuel                15
hakymulla                       16
protestant-kali                 16
impressive-yodharin             16
bigfish                         17
happy-mike                      17
etothexipi                      18
permanent-nosa                  19
poised-endre                    19
divine-azam                     20
primitive-renato                21
eerie-ilias                     21
worthwhile-anybody              22
relaxed-robert                  22
deleted-5340                    22
b0yindab0x                      23
skhotijah                       24
realistic-nur-rahman            24
lexical-rocket                  25
easy-anas                       25
thetansquared                   26
smoggy-mahcih                   26
random-boost                    26
prominent-yokuda                26
magnetic-oleksandr              27
intense-christos                27
calm-juraj                      28
numeraibr                       28
scattered-col                   29
uuazed                          29
adjacent-diego                  30
swish                           31
popular-ravi                    32
correlator                      32
closed-charles                  32
joakim                          33
well-known-data                 34
linear-min                      35
anxious-james                   36
innovative-elena                36
remarkable-zohre                37
single-hanna                    37
dying-david                     37
vocational-tiger                38
immense-william                 39
subtle-majid                    39
xgilbert                        39
blushing-tutut                  39
calm-sina                       40
implicit-blade                  40
ahan-terminator                 41
todayis-felix                   41
usamabuttar                     42
creative-alexandre              42
super-maha                      42
intact-kegol                    43
bloody-xxjoker                  44
polish-roxa-nime                45
liquid-zoli                     45
equal-dean                      45
black-bruni                     46
worldwide-jeremy                47
rdupilon                        48
datacrunch 2025 153 218
trottefox                       1
mashrur-sakif                   2
semantic-hu                     3
faithful-puretwin               3
evagian                         4
right-pachara                   5
unfair-thananya                 5
bitter-krittanut                5
intense-christos                6
yellow-filip                    7
etothexipi                      7
permanent-nosa                  8
amused-david                    8
vast-chananyu                   9
grubby-borit                    9
spicy-questo                    10
innovative-elena                10
tarandros                       11
video-taped-grzegorz            12
joakim                          13
disturbed-simon                 14
crowded-anirban                 14
artificial-suda                 14
clever-tanirika                 15
great-debbi                     15
impressive-yodharin             16
golden-maricar                  17
realistic-nur-rahman            17
noob-saibot                     18
giras                           18
philosophical-ronny             18
adorable-phuong                 18
fastafboi                       18
primitive-renato                19
blushing-tutut                  19
random-boost                    19
latin-sumalee                   20
melted-panat                    20
regonn                          21
anxious-james                   22
multiple-t                      23
loose-hung                      23
coolplay                        24
lcrm                            24
artistic-ivan                   24
ahan-terminator                 24
eerie-ilias                     25
bonom                           25
numeraibr                       26
duuscha                         26
bloody-xxjoker                  26
coastal                         27
bigfish                         28
implicit-blade                  29
single-hanna                    30
popular-ravi                    30
clot7213                        31
encouraging-ryan                31
linear-min                      31
contently-curious               32
smoggy-mahcih                   32
senior-dewi                     33
deleted-5340                    33
selective-zhu                   33
naik-abhijit                    34
rough-aika                      34
vocational-tiger                35
uuazed                          36
marginal-larry                  37
usamabuttar                     37
ltamas97                        37
equal-dean                      38
furious-bs                      39
intact-kegol                    39
hakymulla                       39
calm-juraj                      39
pencil                          40
static-anurak                   41
fit-gustavo                     42
inadequate-ahmad                43
historic-joe                    43
ghiffaryr                       43
liquid-zoli                     43
b0yindab0x                      44
satyummm                        45
xgilbert                        45
alo                             46
polish-roxa-nime                47
fahrenheit                      47
prominent-yokuda                48
correlator                      49
rdupilon                        49
black-bruni                     49
kat                             49
skhotijah                       50
anonymous-manuel                50
scrawny-raveesh                 50
swish                           50
supreme-kaow                    50
calm-sina                       51
todayis-felix                   52
vladislav                       53
rachnogstyle                    53
mass-mohammad                   53
creative-alexandre              54
closed-charles                  54
official-theodorus              55
historic-muhammad-moin          55
yisak                           55
healthy-tan                     56
distinct-hossam                 56
immense-william                 57
adjacent-diego                  58
well-known-data                 59
substantial-alex                59
worldwide-jeremy                59
increased-wang                  60
cold-nasirudeen                 61
magnetic-kansuke                61
cephado                         62
deleted-8212                    62
protestant-kali                 62
soft-eduard                     62
elderly-harry-setiawan          63
wise-hbg                        64
goldfish                        65
high-alpha                      66
poised-endre                    67
relaxed-robert                  68
cyber-bob                       68
marka                           69
happy-mike                      69
dying-david                     70
subtle-rajat                    70
kei-sanada                      70
doriansu                        71
alphawhite                      71
profound-wing                   72
bakura                          73
easy-anas                       74
selective-rrr                   75
pure-avantika                   76
capitaindata                    77
thetansquared                   78
rapid-oleg                      79
mehdi06                         80
real-srinivas                   80
doubtful-afnan                  81
arbaazbeg                       81
fun-leo                         82
absolute-gabriel                82
fotogfreak-sandeep              82
mattfarmermo                    83

In [14]:
from crunch_titles._debug import print_user_ranks

print_user_ranks(print, merged_leaderboards, "tarandros")
print("")
print_user_ranks(print, merged_leaderboards, "cyber-bob")

user                 competition:year                                     rank   usr.cnt
tarandros            adialab:0                                             1.0       375
tarandros            broad-1:0                                             4.0        56
tarandros            broad-2:0                                             1.0        16
tarandros            broad-3:0                                             5.0        15
tarandros            broad-obesity-1:0                                    15.0        67
tarandros            broad-obesity-2:0                                    28.0        72
tarandros            causality-discovery:0                                 2.0       207
tarandros            datacrunch:2024                                       3.0       122
tarandros            datacrunch:2025                                      11.0       218
tarandros            datacrunch-rally:0                                   42.0        47
tarandros            falcon:2025                                           9.0        32
tarandros            falcon:2026                                          11.0        34
tarandros            mid-one:2024                                          4.0        59
tarandros            mid-one:2025                                          3.0        63
tarandros            structural-break:0                                    8.0       584
tarandros            venture-capital-portfolio-prediction:0                3.0        58

user                 competition:year                                     rank   usr.cnt
cyber-bob            broad-obesity-1:0                                     2.0        67
cyber-bob            broad-obesity-2:0                                     5.0        72
cyber-bob            causality-discovery:0                                 8.0       207
cyber-bob            datacrunch:2025                                      68.0       218
cyber-bob            mid-one:2024                                         15.0        59
cyber-bob            mid-one:2025                                         24.0        63
cyber-bob            structural-break:0                                   12.0       584

## compute medals

In [15]:
from crunch_titles import distribute_medals

for (competition, year), positions, user_count in merged_leaderboards:
    distribute_medals(
        positions=positions,
        user_count=user_count,
    )

In [16]:
from crunch_titles._debug import print_medals

print_medals(
    print,
    merged_leaderboards,
    "structural-break",
    2024,
)

login                                       rank  medal
brandao                                        1  GOLD
mario-filho                                    1  GOLD
rafael                                         1  GOLD
joao-peinado                                   1  GOLD
farukcan-saglam                                2  SILVER
abishek                                        2  SILVER
lcrm                                           3  BRONZE
mirko                                          3  BRONZE
valuable-j                                     4  TOP_10_PERCENT
tuah-jihan                                     4  TOP_10_PERCENT
mutian-hong                                    5  TOP_10_PERCENT
guoqin-gu                                      5  TOP_10_PERCENT
giras                                          5  TOP_10_PERCENT
leo-nguyen                                     6  TOP_10_PERCENT
anxious-james                                  6  TOP_10_PERCENT
condor                                         7  TOP_10_PERCENT
tapir                                          7  TOP_10_PERCENT
tarandros                                      8  TOP_10_PERCENT
alright-jho                                    9  TOP_10_PERCENT
impressive-yodharin                            9  TOP_10_PERCENT
stealth-rakesh                                10  TOP_10_PERCENT
afs                                           10  TOP_10_PERCENT
cteceliker                                    11  TOP_10_PERCENT
roberta-becker                                12  TOP_10_PERCENT
cyber-bob                                     12  TOP_10_PERCENT
plutos-farm                                   13  TOP_10_PERCENT
vincent-schuler                               14  TOP_10_PERCENT
moral-timothy                                 14  TOP_10_PERCENT
mrsq                                          16  TOP_10_PERCENT
wagner                                        16  TOP_10_PERCENT
xan                                           17  TOP_10_PERCENT
devnikhilmishra                               18  TOP_10_PERCENT
jamesbond007                                  18  TOP_10_PERCENT
hissing-timothy                               18  TOP_10_PERCENT
passione-boss                                 19  TOP_10_PERCENT
evagian                                       19  TOP_10_PERCENT
unibrow                                       20  TOP_10_PERCENT
major-ying-kai                                20  TOP_10_PERCENT
felix-the-beaver                              21  TOP_10_PERCENT
combined-nikola                               21  TOP_10_PERCENT
yellow-filip                                  22  TOP_10_PERCENT
selective-rrr                                 22  TOP_10_PERCENT
bhosdiwala                                    23  TOP_10_PERCENT
objective-santi                               23  TOP_10_PERCENT
ap-ap                                         24  TOP_10_PERCENT
ronithrashmikara                              24  TOP_10_PERCENT
kat                                           25  TOP_10_PERCENT
many-frank                                    25  TOP_10_PERCENT
mpware                                        26  TOP_10_PERCENT
ducnguyen                                     26  TOP_10_PERCENT
moto                                          26  TOP_10_PERCENT
historic-joe                                  26  TOP_10_PERCENT
gioggiolino                                   27  TOP_10_PERCENT
newbee                                        28  TOP_10_PERCENT
scalar                                        28  TOP_10_PERCENT
divine-kamen                                  29  TOP_10_PERCENT
tight-diego                                   29  TOP_10_PERCENT
light-divyansh                                30  TOP_10_PERCENT
orgkushal                                     30  TOP_10_PERCENT
efficient-swastik                             30  TOP_10_PERCENT
mr-sairaj-nanda                               30  TOP_10_PERCENT
encouraging-ryan                              30  TOP_10_PERCENT
hakymulla                                     31  TOP_10_PERCENT
dexhunter                                     31  TOP_10_PERCENT
j-at-ch                                       32  TOP_10_PERCENT
tomwarrensthereal                             32  TOP_10_PERCENT
digital-emil                                  33  TOP_10_PERCENT
fit-daniel                                    33  TOP_10_PERCENT
ian-kaplan                                    34  TOP_10_PERCENT
minion                                        34  TOP_10_PERCENT
0xzhiqi                                       35  TOP_10_PERCENT
salty-francisco                               35  TOP_10_PERCENT
spicy-questo                                  36  TOP_10_PERCENT
hamzaxmunir                                   36  TOP_10_PERCENT
koufu                                         37  TOP_10_PERCENT
open-kin-ho                                   37  TOP_10_PERCENT
subtle-rajat                                  38  TOP_10_PERCENT
anj-olly                                      38  TOP_10_PERCENT
trottefox                                     39  TOP_10_PERCENT
pansos-ponso                                  40  TOP_10_PERCENT
xcross-ai                                     40  TOP_10_PERCENT
mohamed-saleh                                 41  TOP_10_PERCENT
permanent-nosa                                41  TOP_10_PERCENT
icy-theresa                                   42  TOP_10_PERCENT
evident-owais                                 43  TOP_10_PERCENT
continental-ruslan                            44  TOP_10_PERCENT
moh                                           44  TOP_10_PERCENT
disturbing-priya                              44  TOP_10_PERCENT
hawk-eye                                      44  TOP_10_PERCENT
be-unique                                     45  TOP_10_PERCENT
miscusi                                       45  TOP_10_PERCENT
k-kohv                                        46  TOP_10_PERCENT
outdoor-rana                                  46  TOP_10_PERCENT
detailed-lucca                                47  TOP_10_PERCENT
external-satoshi                              47  TOP_10_PERCENT
babai                                         48  TOP_10_PERCENT
deleted-10341                                 48  TOP_10_PERCENT
psychological-ali                             48  TOP_10_PERCENT
joshwa                                        49  TOP_10_PERCENT
tight-naka                                    49  TOP_10_PERCENT
jade                                          50  TOP_10_PERCENT
unfair-ali                                    51  TOP_10_PERCENT
tropical-alon                                 52  TOP_10_PERCENT
ordinary-manan                                52  TOP_10_PERCENT
magnificent-jai                               53  TOP_10_PERCENT
aventurine                                    53  TOP_10_PERCENT
dsmlkz                                        54  TOP_10_PERCENT
cute-air                                      54  TOP_10_PERCENT
yenvv                                         55  TOP_10_PERCENT
statistical-bhaven                            55  TOP_10_PERCENT
equivalent-yagyik                             56  TOP_10_PERCENT
themuszero                                    57  TOP_10_PERCENT
mikebeth                                      57  TOP_10_PERCENT
lanthorung                                    58  TOP_10_PERCENT
byzantine-yannick                             58  TOP_10_PERCENT
coolplay                                      59  TOP_10_PERCENT
robprofit                                     59  TOP_10_PERCENT
fuseai                                        60  NONE
arpit-goyal                                   60  NONE
crunchycrash                                  61  NONE
waddad                                        61  NONE
entire-ajay                                   62  NONE
nm2025                                        62  NONE
relaxed-robert                                63  NONE
karanshisha101                                63  NONE
rich-nurdaulet                                64  NONE
prominent-yash                                64  NONE
cuddly-phuong                                 65  NONE
motionless-jingming                           66  NONE
holy-gui                                      67  NONE
fit-gustavo                                   67  NONE
balanced-bala                                 67  NONE
disturbed-simon                               68  NONE
santosh-kumar                                 68  NONE
wooden-jacques                                69  NONE
juan-alberto                                  69  NONE
liquid-jelly                                  70  NONE
andnov                                        70  NONE
dr-christian                                  71  NONE
marka                                         72  NONE
swish                                         72  NONE
mathematical-scott                            73  NONE
realistic-nur-rahman                          73  NONE
mighty-yi                                     74  NONE
topsecretai                                   74  NONE
deleted-9307                                  75  NONE
exceptional-zihan                             75  NONE
el-matador                                    76  NONE
qvbnyp007                                     76  NONE
hissing-omar                                  77  NONE
babayaga                                      77  NONE
upstream-salmon                               78  NONE
fun-leo                                       79  NONE
jwu                                           79  NONE
salty-alexander                               80  NONE
major-mahdi                                   80  NONE
voronov-artem                                 81  NONE
disturbed-motthelaw                           81  NONE
green-maru                                    82  NONE
miserable-david                               82  NONE
takfarinesg                                   83  NONE
shallow-artem                                 83  NONE
precious-duc                                  84  NONE
djneetz                                       84  NONE
valus                                         85  NONE
simplexityware                                85  NONE
boris                                         86  NONE
arram                                         86  NONE
gaurav-kap                                    87  NONE
thetansquared                                 87  NONE
fahmiiii                                      88  NONE
sad-dmitry                                    88  NONE
xcesc                                         89  NONE
latency-slayer                                89  NONE
jatayu                                        90  NONE
breakable-souri                               90  NONE
notable-shivam                                90  NONE
kamer-ali                                     91  NONE
artistic-ivan                                 91  NONE
massive-jiaming                               92  NONE
experimental-yash                             93  NONE
middle-reza                                   95  NONE
regular-farzad                                95  NONE
hanisrtp                                      95  NONE
jrbenito                                      96  NONE
failed-physicist                              97  NONE
quick-hao                                     98  NONE
afraid-weixin                                 98  NONE
lei                                           98  NONE
sagarroy                                      99  NONE
furious-bs                                   100  NONE
civil-francis                                101  NONE
adhoc-crosstalk                              101  NONE
draco-storm                                  101  NONE
helpful-jay                                  102  NONE
disastrous-vaibhav                           103  NONE
sure-yoon-tae                                104  NONE
promising-javier                             105  NONE
confident-laura                              105  NONE
pencil                                       106  NONE
contently-curious                            107  NONE
moataz                                       108  NONE
athar-sayed                                  109  NONE
deleted-9724                                 110  NONE
roberock                                     111  NONE
timur-shakurov                               112  NONE
petersz                                      113  NONE
visual-pranay                                115  NONE
great-khaled                                 116  NONE
embarrassed-ishan                            117  NONE
busy-hafiz-rahman                            117  NONE
rahul-m                                      118  NONE
kioqq                                        119  NONE
fotogfreak-sandeep                           120  NONE
thorough-ala-eddine                          121  NONE
xinyu                                        122  NONE
yevgeni                                      123  NONE
shaido987                                    124  NONE
public-alfred                                125  NONE
vladislav                                    126  NONE
random-boost                                 127  NONE
e0nia                                        128  NONE
void-veritas                                 129  NONE
stable-daniel                                130  NONE
fantastic-rajesh                             131  NONE
electronic-martin                            132  NONE
yusef-3yooni                                 133  NONE
sebagam                                      134  NONE
joakim                                       135  NONE
nutritious-redouane                          136  NONE
m-hassan                                     137  NONE
joecarr                                      138  NONE
annual-chakkrit                              139  NONE
monthly-fatin                                140  NONE
elektro                                      141  NONE
smoggy-pawel                                 142  NONE
reliable-shrishty                            143  NONE
mehdi06                                      146  NONE
ravit                                        147  NONE
mattfarmermo                                 148  NONE
high-danil                                   149  NONE
northeast-owl                                150  NONE
chill-guy                                    151  NONE
rajeh                                        151  NONE
immense-omkar                                152  NONE
fascinating-charbel                          153  NONE
relative-duy-anh                             154  NONE
deleted-10719                                155  NONE
tsunami                                      156  NONE
absolute-gabriel                             158  NONE
accepted-fabrizio                            159  NONE
defiant-thierno                              160  NONE
satyummm                                     161  NONE
shankurry                                    161  NONE
current-alexandre                            162  NONE
karg14                                       163  NONE
confused-ronan                               164  NONE
deleted-10079                                165  NONE
mashrur-sakif                                166  NONE
aelkhair                                     167  NONE
ouranos                                      168  NONE
distinct-hossam                              169  NONE
ethical-mauricio                             170  NONE
nevrohelios                                  171  NONE
purple-n                                     172  NONE
zeroday17                                    173  NONE
fahrenheit                                   174  NONE
philosophical-ronny                          175  NONE
mrclnndrd                                    176  NONE
vixhal                                       178  NONE
helpful-amani                                179  NONE
whole-paul                                   181  NONE
straightforward-kristian                     182  NONE
content-romal                                183  NONE
mushy-mohammed                               184  NONE
severe-laminar                               185  NONE
increasing-mathew                            186  NONE
egorbykov                                    187  NONE
usamaasif                                    188  NONE
electric-p-f                                 190  NONE
lllearner                                    191  NONE
tttienthinh                                  192  NONE
rubber-donkey                                193  NONE
technical-sara                               195  NONE
heavy-xuzhou                                 196  NONE
crisp                                        197  NONE
deleted-9151                                 198  NONE
okay-nariman                                 199  NONE
chrishnu                                     200  NONE
sheemamasood381                              201  NONE
itchy-nathan                                 202  NONE
disastrous-aldo                              202  NONE
corgilord                                    203  NONE
noname                                       204  NONE
malo                                         205  NONE
ben-245                                      205  NONE
adbayre                                      205  NONE
exact-adam                                   205  NONE
universal-umair                              207  NONE
annual-pavel                                 208  NONE
ruling-giuseppe                              209  NONE
worldwide-jeremy                             210  NONE
contemporary-arush                           211  NONE
chosen-mohd                                  212  NONE
gregory                                      213  NONE
disappointed-rakia                           214  NONE
overseas-yanbin                              215  NONE
conventional-abhinav                         216  NONE
yousif                                       217  NONE
closed-graham                                218  NONE
blue-luiz                                    219  NONE
durgaprasad762                               220  NONE
scared-ibrahim                               221  NONE
a-tavva                                      222  NONE
dhanu-sree                                   223  NONE
intact-anh                                   224  NONE
rapid-lucifer                                225  NONE
profitable-alex                              226  NONE
outrageous-lama                              227  NONE
correlator                                   228  NONE
gopikachu-3                                  229  NONE
stygue                                       230  NONE
leoxj                                        231  NONE
olzh                                         232  NONE
pratikskarnik                                233  NONE
unsightly-gonzalo                            234  NONE
middle-maryna                                235  NONE
innovative-james                             237  NONE
technical-rakan                              237  NONE
sound-calvin                                 237  NONE
tnt                                          237  NONE
cloudy-alfonso-julian                        238  NONE
rohan-tummala                                239  NONE
atom-heart                                   240  NONE
radooza                                      241  NONE
conceptual-nihar-mahesh                      242  NONE
ahan-terminator                              243  NONE
wilgar                                       244  NONE
rachnogstyle                                 245  NONE
devanshu2901                                 246  NONE
neighbouring-dung                            247  NONE
saif                                         248  NONE

In [17]:
from crunch_titles import count_medals_per_user

medal_counts = count_medals_per_user(
    merged_leaderboards=merged_leaderboards,
)

In [18]:
from crunch_titles._debug import print_medal_counts

print_medal_counts(print, medal_counts)

user                             gold silver bronze top 10%
tarandros                           2      1      3      4
trottefox                           2      -      -      3
plutos-farm                         2      -      -      1
multiple-t                          1      2      -      1
kalin-nonchev                       1      1      1      -
anxious-james                       1      1      -      3
smoggy-mahcih                       1      1      -      1
mutian-hong                         1      -      1      1
coolplay                            1      -      -      3
fwdscttr                            1      -      -      -
agreeable-amine                     1      -      -      -
donald-armstrong                    1      -      -      -
many-frank                          1      -      -      1
marcfm                              1      -      -      -
short-niko                          1      -      -      -
cute-air                            1      -      -      2
right-pachara                       1      -      -      1
joakim                              1      -      -      1
medieval-wajdi                      1      -      -      -
dusty-bluey                         1      -      -      1
mobile-square                       1      -      -      -
swish                               1      -      -      -
brandao                             1      -      -      -
mario-filho                         1      -      -      -
rafael                              1      -      -      -
joao-peinado                        1      -      -      -
cephado                             1      -      -      -
ap-ap                               -      1      1      2
stone-river                         -      1      1      -
fun-robert                          -      1      -      -
eager-manfred                       -      1      -      -
relieved-jingzhe                    -      1      -      -
vetho                               -      1      -      -
cyber-bob                           -      1      -      3
dexhunter                           -      1      -      2
renzo                               -      1      -      -
natural-supercwk                    -      1      -      -
patient-andre                       -      1      -      -
video-taped-grzegorz                -      1      -      3
selective-zhu                       -      1      -      -
kain                                -      1      -      1
mashrur-sakif                       -      1      -      -
fantastic-manoj                     -      1      -      -
main-notmain                        -      1      -      -
relaxed-robert                      -      1      -      1
afs                                 -      1      -      1
farukcan-saglam                     -      1      -      -
abishek                             -      1      -      -
spicy-questo                        -      -      2      4
hj67                                -      -      1      1
big-sen                             -      -      1      -
uninterested-wei                    -      -      1      -
bare-marios                         -      -      1      1
odd-konstantinos                    -      -      1      1
xcross-ai                           -      -      1      1
magnetic-kutsal                     -      -      1      -
comfortable-muhammet-anil           -      -      1      -
dewei                               -      -      1      1
marc                                -      -      1      1
closed-charles                      -      -      1      1
amused-david                        -      -      1      1
semantic-hu                         -      -      1      1
faithful-puretwin                   -      -      1      1
lcrm                                -      -      1      1
primitive-renato                    -      -      1      1
melted-panat                        -      -      1      1
monterey-sardine                    -      -      1      1
medical-rent                        -      -      1      -
radiant-allomancer                  -      -      1      -
fractal-doge                        -      -      1      -
mirko                               -      -      1      -
casual-andy                         -      -      -      1
cautious-mayeul                     -      -      -      1
aesthetic-ge                        -      -      -      1
realistic-yewen                     -      -      -      1
serigne-cisse                       -      -      -      1
strict-siddharth                    -      -      -      1
hablando-en-data-abilio             -      -      -      2
impressive-yodharin                 -      -      -      3
subtle-rajat                        -      -      -      2
be-unique                           -      -      -      2
skipgram                            -      -      -      1
furious-bs                          -      -      -      1
curly-cedric                        -      -      -      1
piyush                              -      -      -      1
proud-anton                         -      -      -      1
mute-adamya                         -      -      -      1
ruling-samarth                      -      -      -      1
nenu                                -      -      -      1
chubby-hari                         -      -      -      1
high-pitched-anas                   -      -      -      1
purple-sajan                        -      -      -      1
breezy-stefan                       -      -      -      1
internal-guna-sekhar                -      -      -      1
miserable-sarath                    -      -      -      1
mukhitson                           -      -      -      1
dying-david                         -      -      -      1
ill-wojciech                        -      -      -      1
everyday-yi                         -      -      -      1
cold-nasirudeen                     -      -      -      2
disturbed-namrata                   -      -      -      1
aniruddhasalve                      -      -      -      1
preliminary-lakshman                -      -      -      1
newbee                              -      -      -      2
sathya                              -      -      -      1
rude-anurag                         -      -      -      1
picky-ricky                         -      -      -      1
digital-huy                         -      -      -      1
prv                                 -      -      -      1
roberta-becker                      -      -      -      2
elaborate-s                         -      -      -      1
defeated-oluwafemi                  -      -      -      1
evagian                             -      -      -      3
aggregate-yu                        -      -      -      1
synapz                              -      -      -      1
tomo                                -      -      -      1
objective-santi                     -      -      -      2
elated-jimmy                        -      -      -      1
profitable-abhishek                 -      -      -      1
subtle-brijesh                      -      -      -      1
semantic-alexander                  -      -      -      1
hi-cdoz                             -      -      -      1
baoduong                            -      -      -      1
amateur-person                      -      -      -      1
fuseai                              -      -      -      1
greenery-cdoz                       -      -      -      1
aleph0                              -      -      -      1
real-yuri                           -      -      -      1
irrelevant                          -      -      -      1
agricultural-sean                   -      -      -      1
blue-luiz                           -      -      -      1
mad-gabriel                         -      -      -      1
deleted-5340                        -      -      -      1
competent-bernardo                  -      -      -      1
thorough-ala-eddine                 -      -      -      1
disturbed-simon                     -      -      -      2
dag-trader                          -      -      -      1
philip                              -      -      -      1
independent-osman-ali               -      -      -      1
modern-mohammed                     -      -      -      1
mezonigor                           -      -      -      1
vast-chananyu                       -      -      -      2
grubby-borit                        -      -      -      2
crowded-anirban                     -      -      -      2
giras                               -      -      -      3
soft-eduard                         -      -      -      1
noob-saibot                         -      -      -      2
kat                                 -      -      -      2
philosophical-ronny                 -      -      -      2
bitter-krittanut                    -      -      -      2
ghiffaryr                           -      -      -      1
ltamas97                            -      -      -      1
substantial-alex                    -      -      -      1
historic-joe                        -      -      -      2
duuscha                             -      -      -      1
unfair-thananya                     -      -      -      1
intense-christos                    -      -      -      1
yellow-filip                        -      -      -      2
etothexipi                          -      -      -      1
permanent-nosa                      -      -      -      2
innovative-elena                    -      -      -      1
artificial-suda                     -      -      -      1
clever-tanirika                     -      -      -      1
great-debbi                         -      -      -      1
golden-maricar                      -      -      -      1
realistic-nur-rahman                -      -      -      1
adorable-phuong                     -      -      -      1
fastafboi                           -      -      -      1
blushing-tutut                      -      -      -      1
random-boost                        -      -      -      1
latin-sumalee                       -      -      -      1
regonn                              -      -      -      1
permanent-prabin-kumar              -      -      -      1
korean-mohamed                      -      -      -      2
thetansquared                       -      -      -      1
valuable-j                          -      -      -      1
guoqin-gu                           -      -      -      1
leo-nguyen                          -      -      -      1
tuah-jihan                          -      -      -      1
alright-jho                         -      -      -      1
stealth-rakesh                      -      -      -      1
cteceliker                          -      -      -      1
vincent-schuler                     -      -      -      1
mrsq                                -      -      -      1
xan                                 -      -      -      1
devnikhilmishra                     -      -      -      1
passione-boss                       -      -      -      1
unibrow                             -      -      -      1
felix-the-beaver                    -      -      -      1
bhosdiwala                          -      -      -      1
mpware                              -      -      -      1
ducnguyen                           -      -      -      1
moto                                -      -      -      1
gioggiolino                         -      -      -      1
divine-kamen                        -      -      -      1
light-divyansh                      -      -      -      1
orgkushal                           -      -      -      1
efficient-swastik                   -      -      -      1
mr-sairaj-nanda                     -      -      -      1
hakymulla                           -      -      -      1
j-at-ch                             -      -      -      1
digital-emil                        -      -      -      1
ian-kaplan                          -      -      -      1
0xzhiqi                             -      -      -      1
koufu                               -      -      -      1
hamzaxmunir                         -      -      -      1
pansos-ponso                        -      -      -      1
mohamed-saleh                       -      -      -      1
salty-francisco                     -      -      -      1
continental-ruslan                  -      -      -      1
moh                                 -      -      -      1
disturbing-priya                    -      -      -      1
k-kohv                              -      -      -      1
detailed-lucca                      -      -      -      1
babai                               -      -      -      1
deleted-10341                       -      -      -      1
joshwa                              -      -      -      1
ronithrashmikara                    -      -      -      1
selective-rrr                       -      -      -      1
tropical-alon                       -      -      -      1
magnificent-jai                     -      -      -      1
dsmlkz                              -      -      -      1
yenvv                               -      -      -      1
wagner                              -      -      -      1
themuszero                          -      -      -      1
lanthorung                          -      -      -      1
tomwarrensthereal                   -      -      -      1
anj-olly                            -      -      -      1
encouraging-ryan                    -      -      -      1
condor                              -      -      -      1
moral-timothy                       -      -      -      1
statistical-bhaven                  -      -      -      1
hawk-eye                            -      -      -      1
fit-daniel                          -      -      -      1
scalar                              -      -      -      1
tapir                               -      -      -      1
jamesbond007                        -      -      -      1
hissing-timothy                     -      -      -      1
major-ying-kai                      -      -      -      1
combined-nikola                     -      -      -      1
tight-diego                         -      -      -      1
minion                              -      -      -      1
open-kin-ho                         -      -      -      1
icy-theresa                         -      -      -      1
evident-owais                       -      -      -      1
miscusi                             -      -      -      1
outdoor-rana                        -      -      -      1
external-satoshi                    -      -      -      1
psychological-ali                   -      -      -      1
tight-naka                          -      -      -      1
jade                                -      -      -      1
unfair-ali                          -      -      -      1
ordinary-manan                      -      -      -      1
aventurine                          -      -      -      1
equivalent-yagyik                   -      -      -      1
mikebeth                            -      -      -      1
byzantine-yannick                   -      -      -      1
robprofit                           -      -      -      1
scirpus                             -      -      -      1
contently-curious                   -      -      -      1

## compute titles

### grandmasters

In [19]:
from crunch_titles._title import compute_grandmasters

grandmaster_user_ids = compute_grandmasters(
    medal_counts=medal_counts,
)

len(grandmaster_user_ids)

11

### masters

In [20]:
from crunch_titles._title import compute_masters

master_user_ids = compute_masters(
    medal_counts=medal_counts, 
    grandmasters=grandmaster_user_ids,
)

len(master_user_ids)

26

### experts

In [21]:
from crunch_titles._title import compute_experts

expert_user_ids = compute_experts(
    medal_counts=medal_counts,
    grandmasters=grandmaster_user_ids,
    masters=master_user_ids,
)

len(expert_user_ids)

34

### ranked

In [22]:
from crunch_titles._title import compute_ranked

ranked_user_ids = compute_ranked(
    medal_counts=medal_counts,
    grandmasters=grandmaster_user_ids,
    masters=master_user_ids,
    experts=expert_user_ids,
)

len(ranked_user_ids)

189

### remaining

In [23]:
from crunch_titles._title import compute_titles

remaining_user_ids = compute_titles(
    medal_counts=medal_counts,
    predicate=lambda _: True,
    other_sets=[grandmaster_user_ids, master_user_ids, expert_user_ids, ranked_user_ids]
)

for user, medal_count in medal_counts:
    if user["id"] in remaining_user_ids:
        print(user["login"], medal_count)

assert len(remaining_user_ids) == 0

### statistics

In [24]:
from crunch_titles._debug import print_titles_count

print_titles_count(
    print,
    grandmaster_user_ids,
    master_user_ids,
    expert_user_ids,
    ranked_user_ids,
)

Titles count:
- grandmasters 11
- masters 26
- experts 34
- ranked 189
- total 260

In [25]:
_dfs: List[pandas.DataFrame] = []

for (competition, year), positions, user_count in merged_leaderboards:
    _dfs.append(pandas.DataFrame([
        {
            "competition": f"{competition['name']}:{year}" if year else competition['name'],
            "user": f"{position['user']['id']}.{position['user']['login']}",
            "average": position["average"],
            "participation_count": position["participation_count"],
            "rank": position["rank"],
        }
        for position in positions
    ]))

merged_leaderboards_df = pandas.concat(_dfs, ignore_index=True)
merged_leaderboards_df

,competition,user,average,participation_count,rank
0,adialab,3048.tarandros,1.0,1,1
1,adialab,3738.fun-robert,2.0,1,2
2,adialab,2281.hj67,3.0,1,3
3,adialab,3623.casual-andy,4.0,1,4
4,adialab,2275.cautious-mayeul,5.0,1,5
...,...,...,...,...,...
1947,venture-capital-portfolio-prediction,3529.elaborate-zoe,54.0,1,54
1948,venture-capital-portfolio-prediction,2281.hj67,55.0,1,55
1949,venture-capital-portfolio-prediction,1637.historic-joe,56.0,1,56
1950,venture-capital-portfolio-prediction,4777.capable-jiaming,57.0,1,57
1951,venture-capital-portfolio-prediction,4397.noname,58.0,1,58

In [26]:
pivoted_leaderboards_df = merged_leaderboards_df.pivot(index="user", columns="competition", values="rank")

pivoted_leaderboards_df["gold"] = 0
pivoted_leaderboards_df["silver"] = 0
pivoted_leaderboards_df["bronze"] = 0
pivoted_leaderboards_df["top_10%"] = 0
pivoted_leaderboards_df["top_20%"] = 0

for user, medal_count in medal_counts:
    user_key = f"{user['id']}.{user['login']}"
    pivoted_leaderboards_df.loc[user_key, "gold"] = medal_count.get("GOLD", 0)
    pivoted_leaderboards_df.loc[user_key, "silver"] = medal_count.get("SILVER", 0)
    pivoted_leaderboards_df.loc[user_key, "bronze"] = medal_count.get("BRONZE", 0)
    pivoted_leaderboards_df.loc[user_key, "top_10%"] = medal_count.get("TOP_10_PERCENT", 0)
    pivoted_leaderboards_df.loc[user_key, "top_20%"] = medal_count.get("TOP_20_PERCENT", 0)

pivoted_leaderboards_df.sort_values(by=["gold", "silver", "bronze"], ascending=False, inplace=True)
pivoted_leaderboards_df.to_csv("meta_ranking.csv")

pivoted_leaderboards_df

competition,adialab,broad-1,broad-2,broad-3,broad-obesity-1,broad-obesity-2,causality-discovery,datacrunch-rally,datacrunch:2024,datacrunch:2025,...,mid-one:2024,mid-one:2025,numinous:2026,structural-break,venture-capital-portfolio-prediction,gold,silver,bronze,top_10%,top_20%
user,,,,,,,,,,,,,,,,,,,,,
3048.tarandros,1.0,4.0,1.0,5.0,15.0,28.0,2.0,42.0,3.0,11.0,...,4.0,3.0,NaN,8.0,3.0,2,1,3,4,0
6710.trottefox,NaN,NaN,NaN,NaN,1.0,44.0,21.0,NaN,7.0,1.0,...,NaN,20.0,NaN,39.0,NaN,2,0,0,3,0
9193.plutos-farm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,13.0,NaN,2,0,0,1,0
1529.multiple-t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,23.0,...,27.0,29.0,1.0,NaN,15.0,1,2,0,1,0
7180.kalin-nonchev,NaN,1.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9972.welcome-aditya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,478.0,NaN,0,0,0,0,0
9974.okay-nariman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,199.0,NaN,0,0,0,0,0
9977.purple-n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,172.0,NaN,0,0,0,0,0
9986.leoxj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,231.0,NaN,0,0,0,0,0
9991.horizontal-mohammad-masih,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,339.0,NaN,0,0,0,0,0

# compute full

In [ ]:
from crunch_titles import compute

compute(
    database=database,
    # competition_name=datacrunch["name"],
    competition_name=structural_break["name"],
    # competition_name=structural_break_open_benchmark["name"],
    logger=logger,
)

database.commit()

In [ ]:
from crunch_titles import compute

for competition in competitions:
    compute(
        database=database,
        competition_name=competition["name"],
        logger=logger,
    )

database.commit()

In [28]:
logger.warning("hello")

hello

# insert in database

## cleanup

In [49]:
database.competition.insert("SET FOREIGN_KEY_CHECKS = 0;")
database.competition.insert("TRUNCATE `title_leaderboards`;")
database.competition.insert("TRUNCATE `title_positions`;")
database.competition.insert("UPDATE `users` SET `title` = 'NOVICE';")
database.competition.insert("SET FOREIGN_KEY_CHECKS = 1;")

0

In [50]:
database.commit()

## title positions

In [51]:
for (competition, year), _ in grouped_positions:
    repository.delete_title_leaderboard_by_competition_and_year(competition, year)

for (competition, year), title_positions, user_count in merged_leaderboards:
    title_leaderboard = repository.create_title_leaderboard({
        "competition_id": competition["id"],
        "year": year,
        "week_count": 0,  # TODO!
        "original_size": user_count,
        "size": len(title_positions),
    })

    for position in title_positions:
        repository.create_title_position({
            "leaderboard_id": title_leaderboard["id"],
            "user_id": position["user"]["id"],
            "averaged_rank": position["average"],
            "participation_count": position["participation_count"],
            "meta_rank": position["rank"],
            "medal": position["medal"],
        })

In [52]:
database.commit()

## user's titles

In [59]:
repository.set_title_for_users("GRANDMASTER", grandmaster_user_ids)
repository.set_title_for_users("MASTER", master_user_ids)
repository.set_title_for_users("EXPERT", expert_user_ids)
repository.set_title_for_users("RANKED", ranked_user_ids)

In [60]:
database.commit()

In [58]:
repository.set_title_for_users("RANKED", {1})
# repository.set_title_for_users("GRANDMASTER", {1})
database.commit()